version: "3.8"

services:
  example-frontend:
    image: example-frontend
    ports:
      - 5000:5000
    container_name: example-frontend

  example-backend:
    image: example-backend
    environment:
      - REDIS_HOST=example-redis
    ports:
      - 8080:8080
    container_name: example-backend

  example-redis:
    image: redis
    container_name: example-redis
